# Generated by Django 4.2.6 on 2023-11-03 15:25

import conectese.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessementDailyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('personal_hygiene', models.CharField(choices=[('independent', 'Independente'), ('dependent', 'Dependente'), ('partial_assistence', 'Assistência parcial'), ('other', 'Outra')], max_length=50)),
                ('personal_hygiene_observation', models.TextField(blank=True, null=True)),
                ('dressing', models.CharField(choices=[('independent', 'Independente'), ('dependent', 'Dependente'), ('partial_assistence', 'Assistência parcial'), ('other', 'Outra')], max_length=50)),
                ('dressing_observation', models.TextField(blank=True, null=True)),
                ('feeding', models.CharField(choices=[('independent', 'Independente'), ('dependent', 'Dependente'), ('partial_assistence', 'Assistência parcial'), ('other', 'Outra')], max_length=50)),
                ('feeding_observation', models.TextField(blank=True, null=True)),
                ('locomotion', models.CharField(choices=[('independent', 'Independente'), ('dependent', 'Dependente'), ('partial_assistence', 'Assistência parcial'), ('other', 'Outra')], max_length=50)),
                ('locomotion_observation', models.TextField(blank=True, null=True)),
                ('other_activities', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('static_balance', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterado'), ('other', 'Outro')], max_length=50)),
                ('static_balance_observation', models.TextField(blank=True, null=True)),
                ('dinamic_balance', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterado'), ('other', 'Outro')], max_length=50)),
                ('dinamic_balance_observation', models.TextField(blank=True, null=True)),
                ('march', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada'), ('other', 'Outra')], max_length=50)),
                ('march_observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('main_plainte', models.TextField(blank=True, null=True)),
                ('avant_history', models.TextField(blank=True, null=True)),
                ('actual_history', models.TextField(blank=True, null=True)),
                ('previous_blessures', models.TextField(blank=True, null=True)),
                ('cirurgic_history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMoviment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cervical_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('cervical_moviment_observation', models.TextField(blank=True, null=True)),
                ('shoulder_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('shoulder_moviment_observation', models.TextField(blank=True, null=True)),
                ('elbow_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('elbow_moviment_observation', models.TextField(blank=True, null=True)),
                ('wrist_and_hand_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('wrist_and_hand_moviment_observation', models.TextField(blank=True, null=True)),
                ('spinal_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('spinal_moviment_observation', models.TextField(blank=True, null=True)),
                ('hip_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('hip_moviment_observation', models.TextField(blank=True, null=True)),
                ('knee_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('knee_moviment_observation', models.TextField(blank=True, null=True)),
                ('ankle_and_foot_moviment', models.CharField(choices=[('normal', 'Normal'), ('restrict', 'Restrita'), ('other', 'Outra')], max_length=50)),
                ('ankle_and_foot_moviment_observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPosture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('general_observation', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada'), ('other', 'Outra')], max_length=50)),
                ('other_observation', models.TextField(blank=True, null=True)),
                ('head_alligment', models.CharField(choices=[('normal', 'Normal'), ('anteriorized', 'Anteriorizada'), ('side_inclination', 'Inclinada para um lado'), ('other', 'Outro')], max_length=50)),
                ('head_observation', models.TextField(blank=True, null=True)),
                ('shoulder_alligment', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevados'), ('intern_rotation', 'Rotação interna'), ('extern_rotation', 'Rotação externa'), ('other', 'Outro')], max_length=50)),
                ('shoulder_observation', models.TextField(blank=True, null=True)),
                ('collumn_alligment', models.CharField(choices=[('normal', 'Normal'), ('hiperlordosis', 'Hiperlordose'), ('hipercifosis', 'Hipercifose'), ('scoliosis', 'Escoliose'), ('other', 'Outro')], max_length=50)),
                ('collumn_observation', models.TextField(blank=True, null=True)),
                ('pelvis_alligment', models.CharField(choices=[('normal', 'Normal'), ('anterior_inclination', 'Inclinação anterior'), ('posterior_inclination', 'Inclinação posterior'), ('side_inclination', 'Inclinação lateral'), ('other', 'Outro')], max_length=50)),
                ('pelvis_observation', models.TextField(blank=True, null=True)),
                ('superior_and_inferior_members', models.CharField(choices=[('normal', 'Normal'), ('detour', 'Desvio'), ('other', 'Outro')], max_length=50)),
                ('superior_and_inferior_members_observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tactile_sensitivity', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada'), ('other', 'Outra')], max_length=50)),
                ('tactile_sensitivity_observation', models.TextField(blank=True, null=True)),
                ('termic_sensitivity', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada'), ('other', 'Outra')], max_length=50)),
                ('termic_sensitivity_observation', models.TextField(blank=True, null=True)),
                ('painful_sensitivity', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada'), ('other', 'Outra')], max_length=50)),
                ('painful_sensitivity_observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cervical_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('cervical_strength_observation', models.TextField(blank=True, null=True)),
                ('shoulder_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('shoulder_strength_observation', models.TextField(blank=True, null=True)),
                ('elbow_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('elbow_strength_observation', models.TextField(blank=True, null=True)),
                ('wrist_and_hand_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('wrist_and_hand_strength_observation', models.TextField(blank=True, null=True)),
                ('spinal_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('spinal_strength_observation', models.TextField(blank=True, null=True)),
                ('hip_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('hip_strength_observation', models.TextField(blank=True, null=True)),
                ('knee_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('knee_strength_observation', models.TextField(blank=True, null=True)),
                ('ankle_and_foot_strength', models.CharField(choices=[('normal', 'Normal'), ('weak', 'Fraca'), ('other', 'Outra')], max_length=50)),
                ('ankle_and_foot_strength_observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=14, validators=[conectese.validators.validate_cpf])),
                ('contact_phone', models.CharField(max_length=10, validators=[conectese.validators.validate_phone])),
                ('emergency_phone', models.CharField(max_length=10, validators=[conectese.validators.validate_phone])),
                ('civil_status', models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widower', 'Viúvo(a)')], default='single', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], default='male', max_length=10)),
                ('number_of_lessons', models.IntegerField(default=0, validators=[conectese.validators.validate_positive_number])),
                ('pay_day', models.CharField(blank=True, default=None, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('conducts', models.TextField(blank=True, null=True)),
                ('observations_and_final_comments', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapy_assessments', to='conectese.patient')),
                ('patient_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='conectese.assessementdailyactivities')),
                ('patient_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='conectese.assessmentbalance')),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='conectese.assessmenthistory')),
                ('patient_moviment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviment', to='conectese.assessmentmoviment')),
                ('patient_posture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture', to='conectese.assessmentposture')),
                ('patient_sensitivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity', to='conectese.assessmentsensorial')),
                ('patient_strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strenght', to='conectese.assessmentstrength')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivityAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('patient', models.ManyToManyField(related_name='physical_activity_appointments', to='conectese.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('times_per_week', models.CharField(choices=[('1', '1x por semana'), ('2', '2x por semana'), ('3', '3x por semana'), ('4', '4x por semana'), ('5', '5x por semana')], max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='conectese.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointments', to='conectese.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('presence', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente')], max_length=50)),
                ('pain_plainte', models.TextField()),
                ('equipment', models.CharField(choices=[('reformer', 'Reformer'), ('barrel', 'Barrel'), ('cadillac', 'Cadillac'), ('chair', 'Chair'), ('wall_chair', 'Wall Chair'), ('solo', 'Solo')], max_length=50)),
                ('stretching', models.CharField(choices=[('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores'), ('other', 'Outro')], max_length=50)),
                ('strengthening', models.CharField(choices=[('superior', 'Membros Superiores'), ('inferior', 'Membros Inferiores'), ('other', 'Outro')], max_length=50)),
                ('other_conducts', models.TextField()),
                ('observations', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_evolutions', to='conectese.patient', unique_for_date='date')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentstrength',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_strength', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessmentsensorial',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sensorial', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessmentposture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_posture', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessmentmoviment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_moviment', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_history', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessmentbalance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_balance', to='conectese.patient'),
        ),
        migrations.AddField(
            model_name='assessementdailyactivities',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_evolutions', to='conectese.patient'),
        ),
    ]
