# Generated by Django 4.2.5 on 2023-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectese', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivityappointment',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
