# Generated by Django 4.2.5 on 2023-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectese', '0002_alter_dailyevolution_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widower', 'Viúvo(a)')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], default='male', max_length=10),
        ),
    ]
